### ISSUE TITLE
how to use in koajs v2

### ISSUE THREAD

**Issue by lonelyclick** [aickin/react-dom-stream#12]
when I write this code in koajs v2

```
ReactDOMStream.renderToString(<Foo prop={value}/>).pipe(ctx.res)
```

then error comes

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:422:15)
    at Adler32Stream.ondata (_stream_readable.js:529:20)
    at emitOne (events.js:90:13)
    at Adler32Stream.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Adler32Stream.Readable.push (_stream_readable.js:111:10)
    at Adler32Stream.Transform.push (_stream_transform.js:127:32)
    at Adler32Stream._transform (/Users/ipconfig/dev/react-universal-starter/node_modules/react-dom-stream/lib/ReactServerAsyncRendering.js:61:12)
    at Adler32Stream.Transform._read (_stream_transform.js:166:10)
```

help me!!!

**Comment by jhen0409** [comment]
The ctx.body can be a Stream.

```js
ctx.body = ReactDOMStream.renderToString(<Foo prop={value}/>);
```

**Comment by lonelyclick** [comment]
It's worked,ths
